### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by etinin** [gyf304/ethash-hlsl#1]
hey, did you ever get this working? plugged into ethminer, but the performance seems to be a few orders of magnitude lower than expected. also, the verification part on ETHashMine.hlsl seems to be broken.

**Comment by gyf304** [comment]
I have put this project on the backburner. The verification part is not tested (I think the endianness might be wrong.) Performance-wise: Somewhat acceptable on Nvidia cards, but absolutely horrendous on AMD cards (like 1/10th the performance). This is also the reason for me shelving the project.

**Comment by etinin** [comment]
thank you very much for the prompt response. Yes, the verification part has a simple endianness mistake.
If you could possibly share the example using this and getting acceptable perf on NV cards, I'd very much like to take a look. 

In any case, thank you very much for the assistance.
